# Spins-up an entire local mc-speedrun environment

version: '3.9'
services:
  speed-run-cache:
    image: redis:6.2.6-alpine
  quiz-result-store:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory -port 8000"
    image: "amazon/dynamodb-local:latest"
    working_dir: /home/dynamodblocal
  quiz-completion-queue:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:?Please ensure this is set in .env}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:?Please ensure this is set in .env}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  sign-on:
    depends_on:
      - speed-run-cache
    image: sign-on
    build:
      # sign-on/ as context and dockerfile path relative to it
      context: ../../sign-on/
      dockerfile: Dockerfile
    environment:
      - SIGN_ON_PORT=80
      - JWT_SECRET
      - JWT_ISSUER
      - JWT_AUDIENCE
  speed-run:
    depends_on:
      quiz-completion-queue:
        # Wait for rabbit mq to initialise within the container before starting
        condition: service_healthy
      speed-run-cache:
        condition: service_started
    image: speed-run
    build:
      # speed-run/ as context and dockerfile path relative to it
      context: ../../speed-run/
      dockerfile: Dockerfile
      target: "base"
    environment:
      - SPEED_RUN_PORT=80
      - JWT_SECRET
      - JWT_ISSUER
      - JWT_AUDIENCE
      - REDIS_HOST=speed-run-cache
      - REDIS_PORT=6379
      - QUIZ_DIRECTORY=/quiz-questions
      - NOTIFY_RABBITMQ_HOST=quiz-completion-queue
      - NOTIFY_RABBITMQ_USERNAME=${RABBITMQ_USER:?Please ensure this is set in .env}
      - NOTIFY_RABBITMQ_PASSWORD=${RABBITMQ_PASS:?Please ensure this is set in .env}
      - NOTIFY_QUEUE_NAME=quiz-complete
      - NOTIFY_DESTINATION_TYPE=rabbitmq
    volumes:
      - type: volume
        source: quiz-questions
        target: /quiz-questions
        read_only: true
        volume:
          nocopy: true
    deploy:
      replicas: 2
  question-set-loader:
    image: question-set-loader
    build:
      # question-set-loader/ as context and dockerfile path relative to it
      context: ../../question-set-loader/
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - JWT_SECRET
      - JWT_ISSUER
      - JWT_AUDIENCE
      - LOADER_DST_DIR=/quiz-questions/
    volumes:
      - type: volume
        source: quiz-questions
        target: /quiz-questions
        read_only: false
        volume:
          nocopy: true
  quiz-result-loader:
    image: quiz-result-loader
    build:
      # quiz-result-loader as context and dockerfile path relative to it
      context: ../../quiz-result-loader/
      dockerfile: Dockerfile
    depends_on:
      quiz-completion-queue:
        # Wait for rabbit mq to initialise within the container before starting
        condition: service_healthy
      speed-run-cache:
        condition: service_started
      quiz-result-store:
        condition: service_started
    environment:
      - RABBITMQ_HOST=quiz-completion-queue
      - RABBITMQ_USERNAME=${RABBITMQ_USER:?Please ensure this is set in .env}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASS:?Please ensure this is set in .env}
      - REDIS_HOST=speed-run-cache
      - REDIS_PORT=6379
      - QUESTION_SET_PATH=/question-sets
      - DYNAMODB_ENDPOINT_URL=http://quiz-result-store:8000
    volumes:
      - type: volume
        source: quiz-questions
        target: /question-sets
        read_only: false
        volume:
          nocopy: true
  reverse-proxy:
    depends_on:
      # Depends on all backend services that nginx proxies to since the resolver
      # runs at startup and must be able to find the address corresponding to
      # the container name.
      - sign-on
      - speed-run
      - question-set-loader
    image: reverse-proxy
    build:
      # Repo root as context and dockerfile path relative to it
      context: ../..
      dockerfile: deployment/docker-compose/reverse-proxy/Dockerfile
    ports:
      - "443:443"
    secrets:
      - server-crt.pem
      - server-key.pem

volumes:
  quiz-questions:
    name: mc-speedrun-quiz-questions

secrets:
  server-crt.pem:
    file: secrets/server-crt.pem
  server-key.pem:
    file: secrets/server-key.pem
