version: '3.9'
services:
  redis:
    image: redis:6.2.6-alpine
  sign-on:
    depends_on:
      - redis
    image: sign-on
    build:
      # sign-on/ as context and dockerfile path relative to it
      context: ../sign-on/
      dockerfile: Dockerfile
    environment:
      - SIGN_ON_PORT=80
      - JWT_SECRET=dockercomposesecret
      - JWT_ISSUER=http://sign-on/
      - JWT_AUDIENCE=http://0.0.0.0/
  reverse-proxy:
    depends_on:
      # Depends on all backend services that nginx proxies to since the resolver
      # runs at startup and must be able to find the address corresponding to
      # the container name.
      - sign-on
    image: reverse-proxy
    build:
      # Repo root as context and dockerfile path relative to it
      context: ..
      dockerfile: deployment/reverse-proxy/Dockerfile
      args:
        # This is from the POV of the client side which has to hit nginx proxy first
        - REACT_APP__SIGN_ON_URL=http://localhost:80
    ports:
      - "80:80"